### ISSUE TITLE
Multint.sh bug

### ISSUE THREAD

**Issue by nullvoid413** [xpz3/airgeddonplugins#1]
Airgeddon v11.11

Whenever I choose AP mode on my Alfa AWUS036ACM (MT7612U Chipset) and Monitor on my AWUS036ACH (RTL8812AU Chipset) and whenever I try to use Evil Twin with captive portal, it says my adapter doesn’t support VIF. Because the latest chipset that is selected is always the monitor mode (which is the chipset that doesn’t support VIF).
I think it’s a bug on the code.

Even if I choose the RTL chipset for AP and MT for Monitor (being the MT the latest chosen) it always says that VIF is not supported.

Any help?

**Comment by xpz3** [comment]
I've made this plugin thinking to support rtl chipsets which never supported vif. But then since I didn't own one, i asked help from others who did have one. But no one really made the effort to test and report. So that's the story about rtlxxxx cards. And regarding the vif message, are you using the updated version of the plugin? Also, there has been recent changes in airgeddon that might cause multiple issues with the plugin too. I didn't get time to adapt to the new update. But, if you are getting the vif error message while using the plugin, and you are using the latest version of the plugin, then just ignore that message and move forward to see if evil twin works or not..
Also, since you have acm card, I'd recommend to use ot for ap and deauth(vif) and use the rtl card for dos pursuit mode

**Comment by nullvoid413** [comment]
Yup. That's exactly what I'm doing, using the RTL for pursuit mode and it works perfectly fine.

The thing is, this would be a great plugin to use since my RTL has better range than my MT.
Oh well, I'll try to ignore the error and move to the next step and give you the feedback.

In the meantime, if you want help to update this plugin, lmk and I can run tests for you.
I think this is such a good plugin and can come handy for many, don't let this die :)!

**Comment by xpz3** [comment]
i've silenced the vif message while using the plugin in a recent version and i dont know why you still get that unless you're using an older version of the plugin. Anyway, i've now updated multint.sh plugin to adapt to the changes done in airgeddon on dos_pursuit_mode attack. You can download this airgeddon version from the dev branch of the repo. Then update the plugin and see if it works or not. If, not show me screenshots of errors you encounter

**Comment by xpz3** [comment]
Seems the issue is resolved as no further comments from op
